# Generated by Django 3.0.8 on 2020-08-19 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighborhood',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='neighbors.Neighborhood'),
        ),
    ]
